---
title: "In-text Citations, References and Footnotes"
format: html
author: "Bella"
---

## Hands-on: In-text Citations, References and Footnotes

### Part 1: In-text Citations and References

Below is a snapshot of a paragraph from the tidyverse homepage, with hard-coded in-text citations and reference section.

1.  Replace the hard-coded in-text citations (marked in bold) with Quarto syntax.
    -   You can either search the items using DOI provided, or add the items to your Zotero library.
2.  Set the Reference section to appear right after the paragraph, replacing the "References used" section.
3.  Change the reference style to use APA style (any edition will do). Download the CSL file from <https://github.com/citation-style-language/styles>.

**Paragraph:**

There are a number of projects that are similar in scope to the tidyverse. The closest is perhaps Bioconductor **(Gentleman et al. 2004; Huber et al. 2015)**, which provides an ecosystem of packages that support the analysis of high-throughput genomic data. The tidyverse has similar goals to R itself, but any comparison to the R Project **(R Core Team 2019)** is fundamentally challenging as the tidyverse is written in R, and relies on R for its infrastructure; there is no tidyverse without R! That said, the biggest difference is in priorities: base R is highly focused on stability, whereas the tidyverse will make breaking changes in the search for better interfaces. Another closely related project is data.table by **Dowle and Srinivasan (2019)**, which provides tools roughly equivalent to the combination of dplyr, tidyr, tibble, and readr. data.table prioritises concision and performance.

**References used:**

Huber, W., V. J. Carey, R. Gentleman, S. Anders, M. Carlson, B. S. Carvalho, H. C. Bravo, et al. 2015. “Orchestrating High-Throughput Genomic Analysis with Bioconductor.” *Nature Methods* 12 (2): 115–21. <https://www.nature.com/articles/nmeth.3252>.

Gentleman, R.C., Carey, V.J., Bates, D.M. et al. Bioconductor: open software development for computational biology and bioinformatics. Genome Biol 5, R80 (2004). <https://doi.org/10.1186/gb-2004-5-10-r80>

R Core Team. 2019. *R: A Language and Environment for Statistical Computing*. Vienna, Austria: R Foundation for Statistical Computing. [https://www.R-project.org/](https://www.r-project.org/).

Dowle, Matt, and Arun Srinivasan. 2019. *data.table: Extension of ‘Data.frame‘*. [https://CRAN.R-project.org/package=data.table](https://cran.r-project.org/package=data.table).

### Part 2: Footnotes

1.  Add the URLs to the tidyverse packages mentioned in the paragraph (dplyr, tidyr, tibble, and readr) as footnotes.
