---
title: "Hands-on #4: Figures, Tables and Cross-References"
author: "Danping"
format: 
    html:
        toc: true
        toc-depth: 2
---

## Hands-on #4

### Figures

1.  Open the `04-penguins.qmd` Quarto Document. At the top of the report about Penguins, add a figure with the following settings:
    -   300 pixels wide

    -   right-aligned

    -   include an alt text for accessibility

    -   add a figure ID `#fig-adelie`
2.  Write a paragraph at the end of the document, making reference to the figure `#fig-adelie`

### Tables

1.  Create a table with the following data inside. You can create it in the visual editor, and switch to source editor to observe the formatting of the table!

2.  now, make the second column left aligned

3.  Use R to create a table showing the first 5 rows of the built-in \`mtcars\` dataset. Use \`knitr::kable()\` to format the table. Some codes are provided below.

    \`\`\`{r}

### Two-column Layout

Create a two-column layout:

-   In the left column, insert a figure with proper attributes

-   In the right column, create a table with a caption

-   Try it yourself: in the example below, what does `{.striped and .hover}` do?

| fruit  | price |
|--------|-------|
| apple  | 2.05  |
| pear   | 1.37  |
| orange | 3.09  |

: Fruit prices {.striped .hover}
