---
title: "Hands-on #3: Instructor Version"
Author: "Danping"
format: 
    html:
        toc: true
        toc-depth: 4
        number-sections: false
        #styling options
        theme: default
        # code block options
        highlight-style: "breeze"
        code-line-numbers: true
        code-tools: true
        code-fold: show
        code-overflow: "wrap" #Other option: scroll
        # execution options
        echo: true
        eval: true
        warning: false
        error: false
---

## Hands-on #3

### Instructions

1.  Play around with YAML options and render the document to see the output.

-   Add table of contents `toc: true`

-   change the depth of your Table of Contents, e.g. `toc-depth: 3`

-   Pick a [HTML theme](https://quarto.org/docs/output-formats/html-themes.html) at this link to be applied on your document, e.g. `theme: "chosen theme"`

-   

2.  render with terminal and Quarto console

### Demo

#### Format

```         
---
format: pdf
---
```

::: aside
Try Other options: html, pdf, docx, pptx, revealjs etc.
:::

#### Table of Contents

1.  TOC as a global option:

```         
toc: true
toc-depth: 4
```

2.  TOC for specific format - note the nested layout:

```         
---
format: 
    html:
        toc: true
---
```

3.  Numbered sections

```         
number-sections: true
```

#### Styling

```         
theme: "quartz"
```

#### code & execution related settings

**Hiding code**： hide codes in the output file

Note: this can be override with settings inside individual code blocks, i.e. code chunk options

**Code Fold**: true\|false\|show (fold but initially shown)

```         
format:
  html:
    code-fold: true
    code-summary: "Show the code"
```

**Code Overflow**: wrap\|scroll

```         
format:
  html:
    code-overflow: wrap
```

**Code Tools**: include tools for readers to copy codes or interact with your document

```         
format:
  html:
    code-fold: true
```

```{r}
library(tidyverse)
library(palmerpenguins)
ggplot(penguins, 
       aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point(aes(color = species, shape = species)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(
    title = "Flipper and bill length",
    subtitle = "Dimensions for penguins at Palmer Station LTER",
    x = "Flipper length (mm)", y = "Bill length (mm)",
    color = "Penguin species", shape = "Penguin species"
  ) +
  theme_minimal()
```

```{markdown}
#DEMO YAML Header Options
---
highlight-style: "breeze" 
code-line-numbers: true
code-tools: true
code-fold: show
code-overflow: "wrap" #Other option: scroll

eval: false #whether to run the code for every rendering
echo: true #whether to include code in the rendered document
warning: false #whether to display warnings in the rendered document
error: false #whether to display errors in the rendered document
---
```
